name: ECE374-B SP24
url: https://ecealgo.com/sp24.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  # - key: staff
  #   name: Staff
  # - key: postdoc
  #   name: Researchers
  - key: grad
    name: Graduate Teaching Assistants
  - key: ugrad
    name: Undergraduate Teaching Assistants
  - key: alum
    name: Alumni Teaching Assistants   
  # - key: ugrad-alum
  #   name: Past Undergraduate Students
  # - key: collab
  #   name: Collaborators
  # - key: alum
  #   name: Alumni

# Number of news stories on the front page.
front_page_news: 4

# Base pathname for links.
base: '/sp24.github.io'

# make pages for the colections
collections:
  lectures:
    output: true
  labs:
    output: true
  resources:
    output: true
  policies: 
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: 
  # - title: People
  #   link: /people.html
  - title: Lectures and Labs
    link: /lectures.html    
  - title: Homeworks
    link: /homeworks.html
  - title: Exams
    link: /exams.html    
  - title: Policies
    link: /policies.html
  - title: Schedules
    link: /office_hours.html       